name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.15"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Test with pytest + behave
        run: |
          uv run pytest --cov-report term-missing --cov=opcdiag --cov=tests tests
          uv run behave
